# Generated by Django 4.2.7 on 2024-01-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli_vj', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_vj', models.CharField(max_length=100)),
                ('apellido_vj', models.CharField(max_length=150)),
                ('nombre_vj', models.CharField(max_length=150)),
                ('direccion_vj', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_in_vj', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vj', models.CharField(max_length=100)),
                ('categoria_vj', models.CharField(max_length=150)),
                ('fechacadu_vj', models.DateField()),
                ('precio_vj', models.FloatField()),
                ('imagen_in_vj', models.FileField(blank=True, null=True, upload_to='ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_pla_vj', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vj', models.CharField(max_length=150)),
                ('calorias_vj', models.CharField(max_length=150)),
                ('descripcion_vj', models.CharField(max_length=150)),
                ('imagen_pla_vj', models.FileField(blank=True, null=True, upload_to='platillos')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_pro_vj', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vj', models.CharField(max_length=100)),
                ('region_vj', models.CharField(max_length=150)),
                ('capital_vj', models.CharField(max_length=150)),
                ('descripcion_vj', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_ti_vj', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vj', models.CharField(max_length=150)),
                ('descripcion_vj', models.CharField(max_length=150)),
                ('categoria_vj', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_re_vj', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vj', models.CharField(max_length=150)),
                ('tiempoprepa_vj', models.CharField(max_length=150)),
                ('dificultad_vj', models.CharField(max_length=150)),
                ('descripcion_vj', models.CharField(max_length=150)),
                ('ingrediente_vj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.ingrediente')),
                ('platillo_vj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='platillo',
            name='tipo_vj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.tipo'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pe_vj', models.AutoField(primary_key=True, serialize=False)),
                ('fechape_vj', models.DateField()),
                ('estadope_vj', models.CharField(max_length=150)),
                ('metodopago_vj', models.CharField(max_length=150)),
                ('observacion_vj', models.CharField(max_length=150)),
                ('cliente_vj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_de_vj', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vj', models.FloatField()),
                ('preciounitario_vj', models.FloatField()),
                ('descuento_vj', models.FloatField()),
                ('total_vj', models.FloatField()),
                ('pedido_vj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.pedido')),
                ('platillo_vj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_vj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.provincia'),
        ),
    ]
